options:
  # Global options
  control-node-selector:
    description: |
      Specifies to which nodes this charm adds the aws-ccm daemonsets
      Declare node labels in key=value format, separated by spaces.
      It's also valid to not have a value, this is interpretted as an empty string.

      Required if not related to kubernetes-control-plane:kube-control

      e.g. 
        node-role.kubernetes.io/control-plane=custom-value
        node-role.kubernetes.io/control-plane=
    type: string

  provider-release:
    type: string
    description: |
      Specify the version of cloud-provider as defined by the `releases`
      directory of https://github.com/kubernetes/cloud-provider-aws/

      example)
        juju config aws-cloud-provider provider-release='v1.26.1'
      
      A list of supported versions is available through the action:
        juju run-action aws-cloud-provider/0 list-releases --wait
      
      To reset by to the latest supported by the charm use:
        juju config aws-cloud-provider --reset provider-release
      
      The current release deployed is available by viewing
        juju status aws-cloud-provider

  controller-extra-args:
    type: string
    default: ""
    description: |
      Space separated list of flags and key=value pairs that will be passed as arguments to
      aws-cloud-controller-manager. For example a value like this:
        cluster_cidr=192.160.0.0/16 v=3
      will result in aws-cloud-controller-manager being run with the following options:
        --cluster_cidr=192.160.0.0/16 --v=3
